"""add subscriptions table

Revision ID: 0e7db1bf8ef8
Revises: 791cb72b610a
Create Date: 2026-09-03 07:49:48.385925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7db1bf8ef8'
down_revision = '791cb72b610a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'BASIC', 'PRO', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('gateway', sa.Enum('PAYSTACK', 'STRIPE', name='subscriptiongateway'), nullable=True),
    sa.Column('gateway_customer_id', sa.String(length=120), nullable=True),
    sa.Column('gateway_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_gateway_subscription_id'), ['gateway_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_school_id'), ['school_id'], unique=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('related_entity_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('related_entity_id')
        batch_op.drop_column('related_entity_type')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_school_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_gateway_subscription_id'))

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
