"""upgraded enroll

Revision ID: 726a1d93489a
Revises: a1f3478b59a0
Create Date: 2026-09-01 18:37:15.190862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a1d93489a'
down_revision = 'a1f3478b59a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_enrollment_per_session_per_school'), type_='unique')
        batch_op.create_index('uq_active_student_enrollment', ['school_id', 'student_id', 'academic_session_id'], unique=True, sqlite_where=sa.text('withdrawal_date IS NULL'), postgresql_where=sa.text('withdrawal_date IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_index('uq_active_student_enrollment', sqlite_where=sa.text('withdrawal_date IS NULL'), postgresql_where=sa.text('withdrawal_date IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_student_enrollment_per_session_per_school'), ['school_id', 'student_id', 'academic_session_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.drop_column('summary_data')

    # ### end Alembic commands ###
