"""add school_settings table

Revision ID: 791cb72b610a
Revises: c6b4fc1f8a77
Create Date: 2026-09-03 06:29:49.069784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791cb72b610a'
down_revision = 'c6b4fc1f8a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('emblem_url', sa.String(length=500), nullable=True),
    sa.Column('motto', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('principal_name', sa.String(length=150), nullable=True),
    sa.Column('school_stamp_url', sa.String(length=500), nullable=True),
    sa.Column('report_header', sa.Text(), nullable=True),
    sa.Column('report_footer', sa.Text(), nullable=True),
    sa.Column('show_logo_on_report', sa.Boolean(), nullable=False),
    sa.Column('show_student_photo_on_report', sa.Boolean(), nullable=False),
    sa.Column('show_grade_on_report', sa.Boolean(), nullable=False),
    sa.Column('show_attendance_on_report', sa.Boolean(), nullable=False),
    sa.Column('show_teacher_remarks_on_report', sa.Boolean(), nullable=False),
    sa.Column('show_principal_remarks_on_report', sa.Boolean(), nullable=False),
    sa.Column('show_ranking_on_report', sa.Boolean(), nullable=False),
    sa.Column('enable_class_ranking', sa.Boolean(), nullable=False),
    sa.Column('require_result_pin', sa.Boolean(), nullable=False),
    sa.Column('result_pin_length', sa.Integer(), nullable=False),
    sa.Column('public_result_verification_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_settings')
    # ### end Alembic commands ###
