"""onboarding table

Revision ID: a1f3478b59a0
Revises: e91aead4980a
Create Date: 2026-09-01 09:14:41.304171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f3478b59a0'
down_revision = 'e91aead4980a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Enum('SCHOOL_INFO', 'LOCALIZATION', 'ACADEMIC_STRUCTURE', 'GRADING_CONFIG', 'PROMOTION_CONFIG', 'ADMIN_ACCOUNT', 'REVIEW', 'DONE', name='onboardingstep'), nullable=False),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_progress_school_id'), ['school_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_progress_school_id'))

    op.drop_table('onboarding_progress')
    # ### end Alembic commands ###
