"""Initial migration

Revision ID: c6b4fc1f8a77
Revises: 
Create Date: 2026-09-02 11:34:16.952091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b4fc1f8a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['admin_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_enrollments_academic_session_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_student_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_enrollments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_academic_session_id'), ['academic_session_id'], unique=False)

    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_user_id')

    # ### end Alembic commands ###
