"""initial migrate

Revision ID: e91aead4980a
Revises: f9cc49cebbea
Create Date: 2026-09-01 08:31:14.931445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91aead4980a'
down_revision = 'f9cc49cebbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('num_code', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_stages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('num_code')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
