"""fix student enrollment uniqueness

Revision ID: ff6478ae9256
Revises: 04ecf4e69569
Create Date: 2026-09-01 19:13:47.460039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6478ae9256'
down_revision = '04ecf4e69569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_enrollments_academic_session_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_student_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_enrollments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_academic_session_id'), ['academic_session_id'], unique=False)

    # ### end Alembic commands ###
