import pytest

from school_app.extensions import db as _db
from school_app.models.school_settings import SchoolSettings


# ======================================================================
# HELPERS
# ======================================================================

def _json(response):
    assert response.is_json, response.get_data(as_text=True)
    return response.get_json()


# ======================================================================
# GET SETTINGS
# ======================================================================

def test_get_settings_returns_default_settings(admin_client, school):
    response = admin_client.get(f"/settings/{school.id}")
    assert response.status_code == 200

    data = _json(response)
    assert data["school_id"] == school.id
    assert data["logo_url"] is None
    assert data["emblem_url"] is None
    assert data["motto"] is None

    assert data["show_logo_on_report"] is True
    assert data["show_student_photo_on_report"] is True
    assert data["show_grade_on_report"] is True
    assert data["show_attendance_on_report"] is True
    assert data["show_teacher_remarks_on_report"] is True
    assert data["show_principal_remarks_on_report"] is False
    assert data["show_ranking_on_report"] is False
    assert data["enable_class_ranking"] is False

    assert data["require_result_pin"] is False
    assert data["result_pin_length"] == 4
    assert data["public_result_verification_enabled"] is True
    assert data["notification_preferences"] == {}


def test_get_settings_returns_existing_settings(admin_client, school, school_settings):
    response = admin_client.get(f"/settings/{school.id}")
    assert response.status_code == 200

    data = _json(response)
    assert data["school_id"] == school.id
    assert data["show_logo_on_report"] is True
    assert data["show_student_photo_on_report"] is True
    assert data["show_grade_on_report"] is True
    assert data["show_attendance_on_report"] is True
    assert data["require_result_pin"] is False
    assert data["result_pin_length"] == 4
    assert data["public_result_verification_enabled"] is True


def test_get_settings_missing_school_returns_404(admin_client):
    response = admin_client.get("/settings/999999")
    assert response.status_code == 404


# ======================================================================
# BRANDING
# ======================================================================

def test_update_branding(admin_client, school):
    payload = {
        "logo_url": "https://example.com/logo.png",
        "emblem_url": "https://example.com/emblem.png",
        "motto": "Excellence Through Knowledge",
        "description": "A great school",
        "address": "123 School Road",
        "phone": "08012345678",
        "contact_email": "school@example.com",
        "website": "https://example.com",
        "primary_color": "#112233",
        "secondary_color": "#445566",
        "principal_name": "John Doe",
        "school_stamp_url": "https://example.com/stamp.png",
        "report_header": "OFFICIAL SCHOOL REPORT",
        "report_footer": "Generated by School Management System",
    }

    response = admin_client.patch(f"/settings/{school.id}/branding", json=payload)
    assert response.status_code == 200

    data = _json(response)
    for key, value in payload.items():
        assert data[key] == value


def test_update_branding_only_changes_supplied_fields(admin_client, school):
    response = admin_client.patch(f"/settings/{school.id}/branding", json={"motto": "New Motto"})
    assert response.status_code == 200

    data = _json(response)
    assert data["school_id"] == school.id
    assert data["motto"] == "New Motto"
    assert data["logo_url"] is None
    assert data["emblem_url"] is None
    assert data["phone"] is None
    assert data["contact_email"] is None


def test_update_branding_rejects_overlong_values(admin_client, school):
    response = admin_client.patch(f"/settings/{school.id}/branding", json={"motto": "x" * 256})
    assert response.status_code == 400


# ======================================================================
# REPORT CARD SETTINGS
# ======================================================================

def test_update_report_card_settings(admin_client, school):
    payload = {
        "show_logo_on_report": False,
        "show_student_photo_on_report": False,
        "show_grade_on_report": False,
        "show_attendance_on_report": False,
        "show_teacher_remarks_on_report": False,
        "show_principal_remarks_on_report": True,
        "show_ranking_on_report": True,
        "enable_class_ranking": True,
    }

    response = admin_client.patch(f"/settings/{school.id}/report-card", json=payload)
    assert response.status_code == 200

    data = _json(response)
    for key, value in payload.items():
        assert data[key] is value


def test_update_report_card_settings_only_changes_supplied_fields(admin_client, school):
    response = admin_client.patch(f"/settings/{school.id}/report-card", json={"show_ranking_on_report": True})
    assert response.status_code == 200

    data = _json(response)
    assert data["show_ranking_on_report"] is True
    assert data["show_logo_on_report"] is True
    assert data["show_student_photo_on_report"] is True
    assert data["show_grade_on_report"] is True
    assert data["show_attendance_on_report"] is True
    assert data["show_teacher_remarks_on_report"] is True
    assert data["show_principal_remarks_on_report"] is False
    assert data["enable_class_ranking"] is False


# ======================================================================
# RESULT ACCESS SETTINGS
# ======================================================================

def test_update_result_access_settings(admin_client, school):
    payload = {
        "require_result_pin": True,
        "result_pin_length": 6,
        "public_result_verification_enabled": False,
    }

    response = admin_client.patch(f"/settings/{school.id}/result-access", json=payload)
    assert response.status_code == 200

    data = _json(response)
    assert data["require_result_pin"] is True
    assert data["result_pin_length"] == 6
    assert data["public_result_verification_enabled"] is False


@pytest.mark.parametrize("pin_length", [3, 11])
def test_update_result_access_rejects_invalid_pin_length(admin_client, school, pin_length):
    response = admin_client.patch(f"/settings/{school.id}/result-access", json={"result_pin_length": pin_length})
    assert response.status_code == 400


# ======================================================================
# NOTIFICATION PREFERENCES
# ======================================================================

def test_update_notification_preferences(admin_client, school):
    payload = {
        "preferences": {
            "RESULT": {"email": True, "sms": False, "push": True, "in_app": True},
            "ATTENDANCE": {"email": True, "sms": True},
        }
    }

    response = admin_client.patch(f"/settings/{school.id}/notifications", json=payload)
    assert response.status_code == 200

    data = _json(response)
    assert data["notification_preferences"] == payload["preferences"]


def test_update_notification_preferences_merges_types(admin_client, school, school_settings):
    with admin_client.c.application.app_context():
        settings = _db.session.get(SchoolSettings, school_settings.id)
        settings.notification_preferences = {
            "RESULT": {"email": True},
            "ATTENDANCE": {"sms": True},
        }
        _db.session.commit()

    response = admin_client.patch(f"/settings/{school.id}/notifications", json={"preferences": {"FEES": {"email": True}}})
    assert response.status_code == 200

    data = _json(response)
    assert data["notification_preferences"] == {
        "RESULT": {"email": True},
        "ATTENDANCE": {"sms": True},
        "FEES": {"email": True},
    }


def test_update_notification_preferences_merges_channels(admin_client, school, school_settings):
    with admin_client.c.application.app_context():
        settings = _db.session.get(SchoolSettings, school_settings.id)
        settings.notification_preferences = {
            "RESULT": {"email": True, "sms": True, "push": True}
        }
        _db.session.commit()

    response = admin_client.patch(f"/settings/{school.id}/notifications", json={"preferences": {"RESULT": {"email": False}}})
    assert response.status_code == 200

    data = _json(response)
    assert data["notification_preferences"]["RESULT"] == {
        "email": False,
        "sms": True,
        "push": True,
    }


def test_update_notification_preferences_requires_preferences(admin_client, school):
    response = admin_client.patch(f"/settings/{school.id}/notifications", json={})
    assert response.status_code == 400


def test_update_notification_preferences_rejects_non_boolean_values(admin_client, school):
    response = admin_client.patch(f"/settings/{school.id}/notifications", json={"preferences": {"RESULT": {"email": "yes"}}})
    assert response.status_code in (200, 400)


# ======================================================================
# RESET NOTIFICATION PREFERENCES
# ======================================================================

def test_reset_notification_preferences(admin_client, school):
    update_response = admin_client.patch(f"/settings/{school.id}/notifications", json={
        "preferences": {
            "RESULT": {"email": True, "sms": True},
            "ATTENDANCE": {"in_app": True},
        }
    })
    assert update_response.status_code == 200

    response = admin_client.post(f"/settings/{school.id}/notifications/reset")
    assert response.status_code == 200

    data = _json(response)
    assert data["notification_preferences"] == {}


def test_reset_notification_preferences_is_idempotent(admin_client, school):
    response = admin_client.post(f"/settings/{school.id}/notifications/reset")
    assert response.status_code == 200
    assert _json(response)["notification_preferences"] == {}

    response = admin_client.post(f"/settings/{school.id}/notifications/reset")
    assert response.status_code == 200
    assert _json(response)["notification_preferences"] == {}


# ======================================================================
# RESPONSE CONTRACT & PERSISTENCE
# ======================================================================

def test_settings_response_contains_all_expected_fields(admin_client, school):
    response = admin_client.get(f"/settings/{school.id}")
    assert response.status_code == 200

    expected_fields = {
        "school_id", "logo_url", "emblem_url", "motto", "description",
        "address", "phone", "contact_email", "website", "primary_color",
        "secondary_color", "principal_name", "school_stamp_url", "report_header",
        "report_footer", "show_logo_on_report", "show_student_photo_on_report",
        "show_grade_on_report", "show_attendance_on_report", "show_teacher_remarks_on_report",
        "show_principal_remarks_on_report", "show_ranking_on_report", "enable_class_ranking",
        "require_result_pin", "result_pin_length", "public_result_verification_enabled",
        "notification_preferences",
    }
    assert expected_fields.issubset(_json(response).keys())


def test_settings_are_persisted_after_route_update(admin_client, school):
    response = admin_client.patch(f"/settings/{school.id}/branding", json={
        "motto": "Persistent Motto",
        "phone": "08000000000",
    })
    assert response.status_code == 200

    with admin_client.c.application.app_context():
        settings = SchoolSettings.query.filter_by(school_id=school.id).first()
        assert settings is not None
        assert settings.motto == "Persistent Motto"
        assert settings.phone == "08000000000"


def test_settings_routes_require_authentication(client, school):
    response = client.get(f"/settings/{school.id}")
    assert response.status_code == 401